import React from "react";
import ReactDOM from "react-dom";
import App from "./App";
import "./App.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap/dist/js/bootstrap.min.js";
import { createRoot } from 'react-dom/client';
const el = document.getElementById("app");
const root = createRoot(el);
root.render(<App />);